services:
  vert:
    container_name: vert
    image: ghcr.io/vert-sh/vert:latest
    build:
      context: .
      args:
        PUB_HOSTNAME: localhost:5173
        PUB_PLAUSIBLE_URL: https://convert.gangoke.app
        PUB_ENV: production
        PUB_DISABLE_ALL_EXTERNAL_REQUESTS: 'false'
        PUB_VERTD_URL: https://vertd.gangoke.app
        PUB_DONATION_URL: https://convert.gangoke.app
        PUB_STRIPE_KEY: 'aaa'
    restart: unless-stopped
    ports:
      - 3000:80
